### ISSUE TITLE
Issue on page /orbital-mechanics/Lecture2/Lecture2.html

### ISSUE THREAD

**Issue by OmarE0526** [angadhn/SpacecraftDynamics#40]
![IMG_1959](https://github.com/user-attachments/assets/47a0089a-9cad-495b-b89e-c07e174451c1)
Your issue content here.

**Comment by angadhn** [comment]
What's the issue?

**Comment by Ghoster-555** [comment]
I think the issue is the misspelling of the words 'momentum' and 'given', he underlined them, but they are difficult to see
![{728B2346-E65E-4CFA-A383-B9FB06C72BB5}](https://github.com/user-attachments/assets/52985167-0f51-4332-b18a-f86fcc37322e)
![{BACB2960-A37B-457D-B71F-4CC007384EC3}](https://github.com/user-attachments/assets/ecbc6db3-bc7e-4cc2-a1fa-0fbb2afe577b)

**Comment by angadhn** [comment]
Thanks- fixed!
